config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


Rails.application.routes.draw do
  devise_for :users
  resources :friends
  # get 'home/index'



   root  'friends#index'



  get   'home/about'    




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord

	belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


         has_many :friends

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]
  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def correct_user

        @friend = current_user.friends.find_by(id: params[:id]) 
        redirect_to friends_path, notice: "Not Authorized To Edit This Friend" if @friend.nil?
  end 



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end


  def about
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group mt-5">
    <%= form.text_field :first_name, class: "form-control shadow", placeholder: "First Name" %>
  </div>

  <div class="field form-group mt-3 ">
    <%= form.text_field :last_name, class: "form-control shadow", placeholder: "Last Name" %>
  </div>

  <div class="field form-group mt-3">
    <%= form.text_field :email, class: "form-control shadow", placeholder: "Email"  %>
  </div>

  <div class="field form-group mt-3 ">
    <%= form.number_field :phone, class: "form-control shadow", placeholder: "Phone Number" %>
  </div>

  <div class="field form-group mt-3">
    <%= form.text_field :twitter, class: "form-control shadow", placeholder: "Twitter" %>
  </div>

  <div class="field form-group mt-3">
    <%= form.number_field :user_id, id: :friend_user_id, class: "form-control shadow", value: current_user.id, type: :hidden %>
  </div>

 


  <div class="actions mt-3 mb-5">
    <%= form.submit class:'btn btn-success' %>
  </div>
<% end %>

app/views/friends/edit.html.erb
<%= render 'form', friend: @friend %>

<%= link_to 'Show', @friend, class: "btn btn-success" %> 
<%= link_to 'Back',  friends_path, class: "btn btn-danger" %>

app/views/friends/index.html.erb
<% if user_signed_in? %>

<table class="table table-success table-striped table-border table-hover">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
     
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>

    <% if friend.user == current_user %>

      <tr>
        <td><%= friend.first_name %>
          <%= friend.last_name %></td>
          
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.twitter %></td> 
      
        <td><%= link_to 'Show', friend, class: "btn btn-success btn-sm" %></td>

        <td><%= link_to 'Edit', edit_friend_path(friend),class: "btn btn-secondary btn-sm" %></td>
        <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %></td>
      </tr>

      <% end %>

    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path, class: "btn btn-success" %>

<% else %>

  
  <%=render template: 'home/index' %>



<%end%>

app/views/friends/new.html.erb
<h1>Add New Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path, class: "btn btn-danger" %>

app/views/friends/show.html.erb
<div class="card text-white bg-success mb-3 " style="max-width: 40rem;">
  <div class="card-header">Details</div>
  <div class="card-body">
   
<p>
  <strong>First name:</strong>
  <%= @friend.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @friend.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @friend.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @friend.phone %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @friend.twitter %>
</p>

<%= link_to 'Edit', edit_friend_path(@friend), class: "btn btn-dark btn-sm" %> 
<%= link_to 'Back', friends_path, class: "btn btn-danger btn-sm" %>

     </div>

app/views/home/about.html.erb
<h1>About Us </h1>

app/views/home/index.html.erb
<div class="container ">
	
<h1 class="title text-center fw-bold">Connecting Humanity for a better World

by sharing experience & knowledge</h1>

<div class="text-center">
	
	<span class="tagline text-warning fs-1">Connect -</span> <span class="tagline text-success fs-1">Socialize -</span> <span class="tagline text-warning fs-1">Share -</span> <span class="tagline text-success fs-1">Learn</span>

</div>


<p class="fs-2 text-secondary text-center">
	Make Your World a Better Place

Friends app is not for hate speech of any kind, spreading

disinformation,violence and incitement of violence
</p>

</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-success" role="alert">
  <%= notice %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FriendsListApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container mt-3">
      <%if notice %>
      <%= render 'layouts/alerts' %>
      <% end %>
        <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-success">
  <div class="container-fluid">
   <%= link_to 'Friends App', root_path,  class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 d-flex">
        


        
      
        <li class="nav-item"> 
        <%= link_to 'About', home_about_path,  class: "nav-link " %>
        </li>

           
        
        <% if user_signed_in? %> 

         <li class="nav-item"> 
        <%= link_to 'Add Friend', new_friend_path,  class: "nav-link " %>
        </li>

         <li class="nav-item"> 
        <%= link_to 'Show Friends', friends_path,  class: "nav-link " %>
        </li>

        

         <li class="nav-item"> 
        <%= link_to 'Edit Profile', edit_user_registration_path, class: "nav-link " %>
        </li>

        <li class="nav-item"> 
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "nav-link " %>
        </li>


       

        <% else %>

     
        <li class="nav-item"> 
        <%= link_to 'Sign Up', new_user_registration_path, class: "nav-link " %>
        </li>

        <li class="nav-item"> 
        <%= link_to 'Sign In', new_user_session_path, class: "nav-link " %>
        </li>

       <% end %>


 
      </ul>
     
        
     
    </div>
  </div>
</nav>